---
- hosts: todoapp
  vars:
    todoapp_user_name: todo-app
    todoapp_user_password: Password
    web_app_repository: https://github.com/timoguic/ACIT4640-todo-app.git
  tasks:

    - name: Install nginx
      become: yes
      package:
        name: nginx
        state: installed

    - name: Copy nginx.conf
      become: yes
      copy:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: nginx
        group: nginx

    - name: Reload nginx
      become: yes
      service:
        name: nginx
        state: reloaded
        enabled: yes  
    
    - name: Install mongodb-server
      become: yes
      package:
        name: mongodb-server
        state: installed

    - name: Enable then start mongod
      become: yes
      service:
        name: mongod
        enabled: yes
        state: started

    - name: Install nodejs
      become: yes
      package:
          name: nodejs
          state: installed

    - name: Install git
      become: yes
      package:
          name: git
          state: installed
    
    - name: Create todoapp user
      become: yes
      user:
        name: "{{todoapp_user_name}}"
        password: "{{todoapp_user_password}}"

    - name: Disable SELinux
      become: yes
      selinux:
        state: disabled

    - name: Clone git repository
      become: yes
      git:
        repo: "{{web_app_repository}}"
        dest: "/home/{{todoapp_user_name}}/app"

    - name: Open HTTP port
      become: yes
      firewalld:
        service: http
        zone: public
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open HTTPS port
      become: yes
      firewalld:
        service: https
        zone: public
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open SSH port
      become: yes
      firewalld:
        service: ssh
        zone: public
        permanent: yes
        state: enabled
        immediate: yes

    - name: npm install
      become: yes
      npm:
        path: "/home/{{todoapp_user_name}}/app"

    - name: Copy database.js
      become: yes
      copy:
        src: ../files/database.js
        dest: "/home/{{todoapp_user_name}}/app/config/database.js"

    - name: Grant permissions
      become: yes
      file:
        path: "/home/{{todoapp_user_name}}"
        state: directory
        recurse: yes
        mode: '0755'
        owner: "{{todoapp_user_name}}"
        group: "{{todoapp_user_name}}"

    - name: Copy todoapp.service
      become: yes
      copy:
        src: ../files/todoapp.service
        dest: /lib/systemd/system/todoapp.service

    - name: Reload daemons
      become: yes
      systemd:
        daemon_reload: yes

    - name: Enable then start todoapp
      become: yes
      service:
        name: todoapp
        enabled: yes
        state: started